name: build centos 8 stream rpm

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/rockylinux:8
    steps:
    - uses: actions/checkout@v2
 
    - name: intall deps
      run: |
        yum -y update && yum -y upgrade
        yum -y install automake autoconf libtool make icu libicu-devel libxml2-devel libuuid-devel fuse-devel net-snmp-devel git python3 wget rpm-build rpmdevtools
        alternatives --set python /usr/bin/python3
 
    - name: build-rpm
      run: |
        rpmdev-setuptree
        cp ltfs.spec ~/rpmbuild/SPECS/
        wget -O ~/rpmbuild/SOURCES/ltfs-2.4.4.0.tar.gz https://github.com/LinearTapeFileSystem/ltfs/archive/v2.4.4.0-10470/ltfs-2.4.4.0.tar.gz
        yum-builddep -y ~/rpmbuild/SPECS/ltfs.spec
        rpmbuild -ba ~/rpmbuild/SPECS/ltfs.spec


    - name: Upload bin directory
      uses: actions/upload-artifact@main
      with:
        name: ltfs-2.4.4.0-10470.x86_64.rpm
        path: /github/home/rpmbuild/RPMS/x86_64/ltfs-2.4.4.0-10470.x86_64.rpm
